branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  Fer-3D-django-blog3-dev:
    branch: null
    repository: null
global:
  application_name: Fer_3D_django_blog3
  branch: null
  default_ec2_keyname: EC2
  default_platform: Python 3.6
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
